sudo: required

services:
  - docker

language: go
go:
  - 1.8

env:
  global:
    - APP=changelog
    - GH=mh-cbon/changelog
    - EMAIL=mh-cbon@users.noreply.github.com
    - JEKYLL=pietromenna/jekyll-cayman-theme
    - MYEMAIL=mh-cbon@users.noreply.github.com # to clean
    - MYAPP=changelog # to clean
    - secure: Aze0dgazElsiZJmFCN/j5hnzn9vcBoUVnHYkz37wWJ1KyDftxFw9VkVXKJslS9+WV+DFs4CFm2IAxh9BB3gXk8GgCyIkwKrrgIYk4qtTDhvI4wLaMn7pwCbsk1H8a+P6gdEyDVV4YXqvXJDPr9nXdJXjiAiLOitZHXjAyijedcCUImJ7oqL6F7/+O8cSMH7YYAxeln82Zn3Kcko6GBJPxCeeFWA27jZfOsQDPkDFz+YJvSafOW101QCSieqQK53rWLGUwgknCLp0/s9yTe2gmdnpYjU1QgFjxIatWoilbJNvXTwZ+XO2S+6QPICnoOQ7BQmJg4KLIz+LPKkF7qPXaoYPdd7pbGraHY92UDcNSCgsD3RX27PUxMX6SE2tEUTxLcGMLZ592Kb+ZUldJ+oTdA40RopGE2DLdpkKHX7LhyBDPq+XCNE2LF/8neqCI8Y42egkl+6gZCIQe4N8yQmrTqaEl6CNYRMmM+FgYNnrr44ItawlgNgvKEmHgl0O1TAIld/j50aULEX+RKjv1XAsm+9zNAMdhjWEyiyXd5tZbLO9okGkqhS0QIm6g+stExdifknjvnaXf0TNA/q+ZUq0wLPYRpJxgQl0leCXJDLZvm8QXFGLRbqpa9ReF7aTfkvw8cS5zI6T/Ttaf+t5xaKfuDZfGdG3lo8GSrCroh2+GoE=

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/mh-cbon/$APP
  - glide install
  - go install

script:
  - go test changelog/*
  - go test tpls/*
  - go test
  - wget -O - https://raw.githubusercontent.com/mh-cbon/gh-pages/master/all.sh | sh -x

before_deploy:
  - mkdir -p build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/changelog main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/changelog main.go
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/create-pkg.sh | GH=$GH sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/create-pkg.sh | GH=$GH sh -xe

after_deploy:
  - wget -O - https://raw.githubusercontent.com/mh-cbon/gh-pages/master/all.sh | sh -x
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/setup-repository.sh | GH=$GH EMAIL=$EMAIL sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/setup-repository.sh | GH=$GH EMAIL=$EMAIL sh -xe

deploy:
  provider: releases
  api_key:
    secure: r85L4eKuTZyn9wIrgloovZE4wctRMLgyZZ2PXeCkRxdA8z4fctySrKGUlWs5nsetEyw2UhBwYVSRj4JjBIp1nsgcEjJZAmlIMl59QvN5PvlGg8OypyUyEJ6oJqt6ve1gyByVUjj+s9HhTqi9VTh27WOAGD6plonNhCj2VHCNHVJbh5WmWVJEbSh7CKwbywSangrmGW9fm/gfpfvmcW5kD+fLrk94vT7XfXbpriGkmUmTzVgOsXpSjZzPIm1e616/bKl4yiSqLXDmIJVNH/5/tzWIE+WkxEWzN2FyfJUbDH+wEWqXq4gmqLva+MdD8h5RkJ+HZBGY6jlf6tBYfR7KsulhEauqUaiuW5WfUBaU6hlXm7eucIPZMHVaTqnnrRDmAgEo7OZqAQrSm+txqxg7hOCdAdPp+tayxSDPbhFwtMn/3wZc0CFUMY4aH1LIZMurZKriojzjqo+jT8wceCzXQPKEHOEeeK2kYsp5rtsB0jUBcM97n1ihOuDrketyyrueVf7vdZ9kpGClP+2HUvoVNrm2PYskVm/aoQSKX+4dD7wWLZpP/MQK1Pbmcvky/p4WbKvquEsqwAT34cT51YjKDfXq1LEnDLxx0qcutEKZMIsX/yMF/pa5QM4Os/a7nVn1kuxIRf5Dn2t5AN4boT3qsYtngXJSyNABuD8hPRHBP+Y=
  file_glob: true
  file:
    - $APP-386.deb
    - $APP-amd64.deb
    - $APP-386.rpm
    - $APP-amd64.rpm
  skip_cleanup: true
  on:
    tags: true
