dist: bionic
os: linux
services:
  - docker

language: go
go:
  - 1.15.6

env:
  jobs:
    - OKARCH=amd64 OSARCH=amd64
    - OKARCH=386 OSARCH=i386
  global:
    - VERSION=${TRAVIS_TAG}
    - GH_USER=${TRAVIS_REPO_SLUG%/*}
    - GH_APP=${TRAVIS_REPO_SLUG#*/}

before_install:
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - glide install
  - go install

script:
  - go test changelog/*
  - go test tpls/*
  - go test

before_deploy:
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - mkdir -p build/$OSARCH
  - GOOS=linux go build --ldflags "-X main.VERSION=$VERSION" -o build/$OSARCH/$GH_APP main.go

deploy:
  provider: releases
  api_key:
    secure: J9oRiOHW2SYlBwk/Ekpgk1EzURG3jTtjlOZ6E/LFAkwQCxpjEQDA0xo5iZWyJb5H2E3g9LToIzUbAFxI5vItCpWXSt0BJCyH/yMlHli6IfdQHOSrqcjWyde9F/Y1Se+8heLdzQtxvsEIUqVjMLnQhQqxN6EfLx/UpVumWALQipFVgMD9dfDJSycRlRF4tL1sCSEMWjdCgyoUBPeIIPthtjkaHH2WynwpitWfwvshDZ2+lHvC+JfoSDPdY+EEe4h/tTcKd20zTZNcKTKBF9sDIMbb0kZIa16JYlp7QguJai4domPahKTPfsZDY6zkHNNMc1NSpO6bUvcYcIsgGHEYciiYUkBlEciFHLyGC6w0UbxXAd0MIK1nMQJ7XMeoz0km2YGWTPJlAn3n4gu9XHHqSPeiV+YUu09qf42L7gEQoYm+w0B14LKGCWoYCQHxuU0T68eOaexe/xnAtGDY0+g+nV4gUsHj6L0WyUNPeu+LnHdHzw2S3dWAltOKvtlBs40YSm1vXQInJwWWMAHyt8SVeMr5+GnyGtpLKg7/U5/tiSEDou8id0lHXxjFxOEzT+PY5mhgjM5UOmv4ekQSAuBZAlV1JYxq2kL/4feWGp1b4V3148wDskCFWSZf+jp0IbrA8qs9LwnhFJado6IGP3W2LlbuQigak5uJQw3SbahRd10=
  file_glob: true
  file:
    - build/$OSARCH/$GH_APP
  skip_cleanup: true
  on:
    tags: true
