language: go
go:
- tip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential lintian -y
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh
  - wget -q -O - --no-check-certificate https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/install.sh | sh
install:
  - cd $GOPATH/src/github.com/mh-cbon/changelog
  - glide install
  - go install
script:
  - go test changelog/*
before_deploy:
  - mkdir -p build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/changelog main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/changelog main.go
  - go-bin-deb generate -a 386 --version ${TRAVIS_TAG} -w pkg-build-386/ -o ${TRAVIS_BUILD_DIR}/changelog-386.deb
  - go-bin-deb generate -a amd64 --version ${TRAVIS_TAG} -w pkg-build-amd64/ -o ${TRAVIS_BUILD_DIR}/changelog-amd64.deb
deploy:
  provider: releases
  api_key:
    secure: r85L4eKuTZyn9wIrgloovZE4wctRMLgyZZ2PXeCkRxdA8z4fctySrKGUlWs5nsetEyw2UhBwYVSRj4JjBIp1nsgcEjJZAmlIMl59QvN5PvlGg8OypyUyEJ6oJqt6ve1gyByVUjj+s9HhTqi9VTh27WOAGD6plonNhCj2VHCNHVJbh5WmWVJEbSh7CKwbywSangrmGW9fm/gfpfvmcW5kD+fLrk94vT7XfXbpriGkmUmTzVgOsXpSjZzPIm1e616/bKl4yiSqLXDmIJVNH/5/tzWIE+WkxEWzN2FyfJUbDH+wEWqXq4gmqLva+MdD8h5RkJ+HZBGY6jlf6tBYfR7KsulhEauqUaiuW5WfUBaU6hlXm7eucIPZMHVaTqnnrRDmAgEo7OZqAQrSm+txqxg7hOCdAdPp+tayxSDPbhFwtMn/3wZc0CFUMY4aH1LIZMurZKriojzjqo+jT8wceCzXQPKEHOEeeK2kYsp5rtsB0jUBcM97n1ihOuDrketyyrueVf7vdZ9kpGClP+2HUvoVNrm2PYskVm/aoQSKX+4dD7wWLZpP/MQK1Pbmcvky/p4WbKvquEsqwAT34cT51YjKDfXq1LEnDLxx0qcutEKZMIsX/yMF/pa5QM4Os/a7nVn1kuxIRf5Dn2t5AN4boT3qsYtngXJSyNABuD8hPRHBP+Y=
  file:
    - changelog-386.deb
    - changelog-amd64.deb
  skip_cleanup: true
  on:
    tags: true
